export const PRELOAD_DEFAULT_DATA = 'PRELOAD_DEFAULT_DATA';
export const SET_SELECTED_DECK = 'SET_SELECTED_DECK';
export const SET_PLAYERS = 'SET_PLAYERS';
export const CHANGE_CARD_AMOUNT = 'CHANGE_CARD_AMOUNT';